create a float array[2,2] array with Fortran-Style order

In [5]:
import numpy as np
np.ndarray(shape=(2,2), dtype='float', order='F')

array([[  2.67276450e+185,   1.75184137e+190],
       [  1.69506143e+190,   9.48819320e+077]])

constructor

In [12]:
np.ndarray(shape=(2,), buffer=np.array([1,2,3]), offset=np.int_().itemsize, dtype=int)

array([2, 3])

ndarray.T

In [14]:
x = np.array([[1,2,3], [4,5, 6]])
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

1-dimension ndarray.T

In [15]:
x = np.array([1,2,3,4])
x.T

array([1, 2, 3, 4])

dtype

In [18]:
x = np.array([1,2,3,4])
print (x.dtype)
print (type(x.dtype))

int32
<class 'numpy.dtype'>


flat

In [25]:
x = np.arange(1, 7).reshape(2, 3)
print(x.flat[3])
print (type(x.flat))

4
<class 'numpy.flatiter'>


imag and real

In [26]:
x = np.sqrt([1+0j, 0+1j])
print (x.imag)
print (x.real)

[ 0.          0.70710678]
[ 1.          0.70710678]


size : number of elements in array
itemsize: length of element
nbytes: total bytes
ndim: number of array dimensions
shape: tuple of array dimensions

strides: tuple of bytes to step in each dimension when traversing an array

In [29]:
y = np.reshape(np.arange(2*3*4), (2,3,4))
print (y.strides)
offset = sum(y.strides * np.array((1,1,1)))
print (offset / y.itemsize)

(48, 16, 4)
17.0


base: base object if memory is from other objects

In [36]:
x = np.array([1,2,3])
print(x.base is None)
y = x[2:]
print (y.base is x)

True
True
