In [18]:
import numpy as np

In [19]:
#min max
z = np.random.random((5,5))
print (z)
zmin,zmax = z.min(), z.max()
print (zmin)
print (zmax)

[[ 0.38125678  0.21228204  0.80024775  0.60075014  0.42571263]
 [ 0.5414915   0.84487953  0.99730092  0.76878902  0.51765049]
 [ 0.07642699  0.16815127  0.65005459  0.10505441  0.67217628]
 [ 0.20362239  0.31162155  0.85740897  0.40443484  0.97672658]
 [ 0.99266493  0.8236577   0.0767001   0.48313578  0.84251114]]
0.0764269872122
0.997300924319


In [21]:
# 归一化
z = np.random.random((5,5))
print (z)
zmin,zmax = z.min(), z.max()
z = (z-zmin)/(zmax-zmin)
print (z)

[[ 0.56907601  0.65541428  0.65513191  0.67616542  0.22478991]
 [ 0.76227238  0.22482328  0.23061636  0.51816544  0.02399675]
 [ 0.30669715  0.61738155  0.42206915  0.4751545   0.45783044]
 [ 0.7593838   0.01049939  0.45749276  0.14311171  0.62635794]
 [ 0.93827166  0.89764283  0.81946223  0.73689433  0.07607985]]
[[ 0.6020622   0.69512197  0.69481761  0.7174886   0.23097319]
 [ 0.81029905  0.23100915  0.23725323  0.54718821  0.01454814]
 [ 0.31925696  0.65412836  0.44361076  0.50082884  0.48215609]
 [ 0.80718559  0.          0.48179212  0.14293628  0.66380357]
 [ 1.          0.95620818  0.87194116  0.7829453   0.07068594]]


In [22]:
# 矩阵相加
z = np.zeros((5,5))
z += np.arange(5)
print (z)

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


In [23]:
#生成0-10之间均匀分布的11个数，包括0和10
z = np.linspace(0, 10, 11, endpoint=True, retstep=True)
print(z)

(array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.]), 1.0)


In [24]:
help(np.linspace)

Help on function linspace in module numpy.core.function_base:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    Parameters
    ----------
    start : scalar
        The starting value of the sequence.
    stop : scalar
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bo

In [14]:
# 交换两行
a = np.arange(25).reshape(5,5)
print (a)
a[[0,1]]=a[[1,0]]
print (a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [15]:
# 找出数组中与给定值最接近的数
z = np.array([[0,1,2,3],[4,5,6,7]])
a = 5.1
print(np.abs(z-a).argmin())

5


In [16]:
# 判断二维矩阵中有没有一整列数为0
z = np.random.randint(0, 3,(2,10))
print (z)
print (z.any(axis=0))

[[0 2 1 1 2 2 2 0 1 2]
 [1 0 1 1 0 0 2 2 0 0]]
[ True  True  True  True  True  True  True  True  True  True]


In [43]:
#生成二维的高斯矩阵
x,y=np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
print (x)
print (y)
D = np.sqrt(x**2+y**2)
print (D)
sigma, mu = 1, 0
a = np.exp(-(D-mu)**2/(2*sigma**2))
print (a)

[[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
